language: objective-c  #1
osx_image: xcode7.2 #2
xcode_project: v2SolutionSwiftTravis.xcodeproj #3
xcode_scheme: v2SolutionSwiftTravis #4
xcode_sdk: iphonesimulator9.2 #5

#command to build the .app for specific scheme
- xctool -workspace "$APP_WORKSPACE_PATH" -scheme "$APP_SCHEME.$APP_BUILD_ENV" -sdk iphoneos -configuration "$APP_BUILD_ENV" OBJROOT="$PWD/build" SYMROOT="$PWD/build" ONLY_ACTIVE_ARCH=NO
#command to run unit test for specific scheme
- xctool test -workspace "$APP_WORKSPACE_PATH" -scheme "$APP_SCHEME.$APP_BUILD_ENV" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
